import streamlit as st
import pandas as pd

# ---------------------------------------------------
# PAGE CONFIG
# ---------------------------------------------------

st.set_page_config(
    page_title="Analytics | AI Hate Speech Detector",
    page_icon="📊",
    layout="wide"
)

# ---------------------------------------------------
# CUSTOM CSS
# ---------------------------------------------------

st.markdown("""
<style>

.main {
    background-color: transparent;
}

.metric-card {
    background: rgba(20, 27, 45, 0.6);
    backdrop-filter: blur(8px);
    padding: 20px;
    border-radius: 20px;
    border: 1px solid rgba(255, 255, 255, 0.05);
    text-align: center;
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    transition: all 0.3s ease;
}

.metric-card:hover {
    transform: translateY(-5px);
    background: rgba(30, 41, 59, 0.8);
    border: 1px solid rgba(0, 229, 255, 0.4);
    box-shadow: 0 8px 25px rgba(0, 229, 255, 0.15);
}

.metric-title {
    font-size: 18px;
    font-weight: bold;
    color: #E2E8F0;
}

.metric-value {
    font-size: 36px;
    font-weight: bold;
    margin-top: 10px;
    background: -webkit-linear-gradient(45deg, #00E5FF, #8B5CF6);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
}

.section-box {
    background: linear-gradient(145deg, rgba(30, 41, 59, 0.8), rgba(15, 23, 42, 0.8));
    backdrop-filter: blur(10px);
    padding: 25px;
    border-radius: 18px;
    border: 1px solid rgba(255, 255, 255, 0.1);
    margin-top: 20px;
    box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3);
}

.footer {
    text-align: center;
    color: gray;
    margin-top: 40px;
}

</style>
""", unsafe_allow_html=True)

# ---------------------------------------------------
# HEADER
# ---------------------------------------------------

st.title("📊 Analytics Dashboard")

st.write("""
Monitor hate speech detection trends, category distribution,
and moderation insights generated by the AI pipeline.
""")

st.markdown("---")

# ---------------------------------------------------
# SAMPLE DATA
# ---------------------------------------------------

data = {
    "Category": ["Offensive", "Neutral", "Toxic", "Slang"],
    "Count": [12, 88, 21, 34]
}

df = pd.DataFrame(data)

# ---------------------------------------------------
# METRICS
# ---------------------------------------------------

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.markdown("""
    <div class="metric-card">
        <div class="metric-title">🧠 Total Analyses</div>
        <div class="metric-value">155</div>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown("""
    <div class="metric-card">
        <div class="metric-title">⚠️ Offensive</div>
        <div class="metric-value">12</div>
    </div>
    """, unsafe_allow_html=True)

with col3:
    st.markdown("""
    <div class="metric-card">
        <div class="metric-title">🔥 Toxic</div>
        <div class="metric-value">21</div>
    </div>
    """, unsafe_allow_html=True)

with col4:
    st.markdown("""
    <div class="metric-card">
        <div class="metric-title">💬 Slang</div>
        <div class="metric-value">34</div>
    </div>
    """, unsafe_allow_html=True)

# ---------------------------------------------------
# CHARTS
# ---------------------------------------------------

st.markdown("<br>", unsafe_allow_html=True)

chart_col1, chart_col2 = st.columns(2)

with chart_col1:

    st.markdown("""
    <div class="section-box">
    <h3>📈 Detection Distribution</h3>
    </div>
    """, unsafe_allow_html=True)

    st.bar_chart(
        df.set_index("Category")
    )

with chart_col2:

    st.markdown("""
    <div class="section-box">
    <h3>📊 Detection Comparison</h3>
    </div>
    """, unsafe_allow_html=True)

    pie_df = pd.DataFrame({
        "Category": ["Neutral", "Flagged"],
        "Count": [88, 67]
    })

    st.area_chart(
        pie_df.set_index("Category")
    )

# ---------------------------------------------------
# TABLE SECTION
# ---------------------------------------------------

st.markdown("---")

st.subheader("🗂️ Detailed Analytics Table")

analytics_df = pd.DataFrame({
    "Text ID": [101, 102, 103, 104, 105],
    "Prediction": [
        "Neutral",
        "Offensive",
        "Toxic",
        "Neutral",
        "Slang"
    ],
    "Confidence": [
        0.91,
        0.87,
        0.79,
        0.95,
        0.74
    ]
})

st.dataframe(
    analytics_df,
    use_container_width=True
)

# ---------------------------------------------------
# INSIGHTS
# ---------------------------------------------------

st.markdown("---")

st.subheader("🔍 AI Insights")

st.info("""
Most flagged content contains:
- Aggressive slang
- Abusive phrases
- Internet toxicity patterns
- Hinglish mixed-language expressions

The system uses:
Whisper + Translation + Transformer Models + Fusion Scoring
""")

# ---------------------------------------------------
# FOOTER
# ---------------------------------------------------

st.markdown("""
<div class="footer">
AI Hate Speech Detection Analytics Dashboard
</div>
""", unsafe_allow_html=True)